# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectDeviceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

class Ui_connetDeviceDialog(object):
    def setupUi(self, connetDeviceDialog):
        connetDeviceDialog.setObjectName("connetDeviceDialog")
        connetDeviceDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(connetDeviceDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(connetDeviceDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_table = QtWidgets.QComboBox(connetDeviceDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_table.setFont(font)
        self.comboBox_table.setObjectName("comboBox_table")
        self.gridLayout.addWidget(self.comboBox_table, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(connetDeviceDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_device = QtWidgets.QComboBox(connetDeviceDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_device.setFont(font)
        self.comboBox_device.setObjectName("comboBox_device")
        self.gridLayout.addWidget(self.comboBox_device, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(connetDeviceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(connetDeviceDialog)
        self.buttonBox.accepted.connect(connetDeviceDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(connetDeviceDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(connetDeviceDialog)

    def retranslateUi(self, connetDeviceDialog):
        _translate = QtCore.QCoreApplication.translate
        connetDeviceDialog.setWindowTitle(_translate("connetDeviceDialog", "Dialog"))
        self.label.setText(_translate("connetDeviceDialog", "升降桌端口："))
        self.label_2.setText(_translate("connetDeviceDialog", "检测设备端口："))

class ConnectDeviceDialog(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_connetDeviceDialog()
        self.ui.setupUi(self)